# Generated by Django 5.2.8 on 2025-11-07 23:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicalhour',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich text notes for this hour; appears after the general prayer on the page.'),
        ),
    ]
